// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/landlady.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务信息
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                               // 服务唯一标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                           // 服务名称
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                                                     // 服务地址
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                                          // 服务端口
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                                                           // 服务标签
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 服务元数据
	Health        bool                   `protobuf:"varint,7,opt,name=health,proto3" json:"health,omitempty"`                                                                      // 健康状态
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                // 注册时间（Unix时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_proto_landlady_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Service) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Service) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

func (x *Service) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 健康检查配置
type HealthCheck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // 健康检查ID
	ServiceId       string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`                                                    // 关联的服务ID
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                                               // 检查类型：http, tcp, grpc, script
	Config          map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 检查配置
	Interval        int64                  `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`                                                                      // 检查间隔（秒）
	Timeout         int64                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                        // 检查超时（秒）
	DeregisterAfter int64                  `protobuf:"varint,7,opt,name=deregister_after,json=deregisterAfter,proto3" json:"deregister_after,omitempty"`                                 // 服务不健康多久后注销（秒）
	LastCheck       int64                  `protobuf:"varint,8,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`                                                   // 上次检查时间（Unix时间戳）
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                                                           // 当前状态：passing, warning, critical
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_landlady_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthCheck) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *HealthCheck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheck) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *HealthCheck) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *HealthCheck) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *HealthCheck) GetDeregisterAfter() int64 {
	if x != nil {
		return x.DeregisterAfter
	}
	return 0
}

func (x *HealthCheck) GetLastCheck() int64 {
	if x != nil {
		return x.LastCheck
	}
	return 0
}

func (x *HealthCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 服务注册请求
type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                            // 服务信息
	HealthCheck   *HealthCheck           `protobuf:"bytes,2,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"` // 健康检查配置（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_proto_landlady_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterServiceRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *RegisterServiceRequest) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

// 服务注册响应
type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 注册成功的服务ID
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_proto_landlady_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 服务注销请求
type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 服务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_proto_landlady_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// 服务注销响应
type DeregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceResponse) Reset() {
	*x = DeregisterServiceResponse{}
	mi := &file_proto_landlady_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceResponse) ProtoMessage() {}

func (x *DeregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 服务更新请求
type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 服务信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_proto_landlady_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateServiceRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

// 服务更新响应
type UpdateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceResponse) Reset() {
	*x = UpdateServiceResponse{}
	mi := &file_proto_landlady_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResponse) ProtoMessage() {}

func (x *UpdateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 服务发现请求
type DiscoverServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // 服务名称
	HealthyOnly   bool                   `protobuf:"varint,2,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"` // 是否只返回健康的服务
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                   // 标签过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverServiceRequest) Reset() {
	*x = DiscoverServiceRequest{}
	mi := &file_proto_landlady_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverServiceRequest) ProtoMessage() {}

func (x *DiscoverServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverServiceRequest.ProtoReflect.Descriptor instead.
func (*DiscoverServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscoverServiceRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

func (x *DiscoverServiceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 服务发现响应
type DiscoverServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // 服务列表
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`  // 是否成功
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`   // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverServiceResponse) Reset() {
	*x = DiscoverServiceResponse{}
	mi := &file_proto_landlady_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverServiceResponse) ProtoMessage() {}

func (x *DiscoverServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverServiceResponse.ProtoReflect.Descriptor instead.
func (*DiscoverServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverServiceResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DiscoverServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DiscoverServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 健康检查请求
type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 服务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_proto_landlady_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{10}
}

func (x *CheckHealthRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// 健康检查响应
type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`    // 健康状态：passing, warning, critical
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_proto_landlady_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{11}
}

func (x *CheckHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckHealthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 服务监控请求
type WatchServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // 服务名称
	HealthyOnly   bool                   `protobuf:"varint,2,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"` // 是否只返回健康的服务
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                   // 标签过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchServiceRequest) Reset() {
	*x = WatchServiceRequest{}
	mi := &file_proto_landlady_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchServiceRequest) ProtoMessage() {}

func (x *WatchServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchServiceRequest.ProtoReflect.Descriptor instead.
func (*WatchServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{12}
}

func (x *WatchServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WatchServiceRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

func (x *WatchServiceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 服务监控响应
type WatchServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // 服务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchServiceResponse) Reset() {
	*x = WatchServiceResponse{}
	mi := &file_proto_landlady_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchServiceResponse) ProtoMessage() {}

func (x *WatchServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_landlady_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchServiceResponse.ProtoReflect.Descriptor instead.
func (*WatchServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_landlady_proto_rawDescGZIP(), []int{13}
}

func (x *WatchServiceResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_proto_landlady_proto protoreflect.FileDescriptor

const file_proto_landlady_proto_rawDesc = "" +
	"\n" +
	"\x14proto/landlady.proto\x12\blandlady\"\x8f\x02\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12/\n" +
	"\x04meta\x18\x06 \x03(\v2\x1b.landlady.Service.MetaEntryR\x04meta\x12\x16\n" +
	"\x06health\x18\a \x01(\bR\x06health\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x02\n" +
	"\vHealthCheck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\x06config\x18\x04 \x03(\v2!.landlady.HealthCheck.ConfigEntryR\x06config\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\x03R\binterval\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x03R\atimeout\x12)\n" +
	"\x10deregister_after\x18\a \x01(\x03R\x0fderegisterAfter\x12\x1d\n" +
	"\n" +
	"last_check\x18\b \x01(\x03R\tlastCheck\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x16RegisterServiceRequest\x12+\n" +
	"\aservice\x18\x01 \x01(\v2\x11.landlady.ServiceR\aservice\x128\n" +
	"\fhealth_check\x18\x02 \x01(\v2\x15.landlady.HealthCheckR\vhealthCheck\"l\n" +
	"\x17RegisterServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"9\n" +
	"\x18DeregisterServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"O\n" +
	"\x19DeregisterServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x14UpdateServiceRequest\x12+\n" +
	"\aservice\x18\x01 \x01(\v2\x11.landlady.ServiceR\aservice\"K\n" +
	"\x15UpdateServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x16DiscoverServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fhealthy_only\x18\x02 \x01(\bR\vhealthyOnly\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"|\n" +
	"\x17DiscoverServiceResponse\x12-\n" +
	"\bservices\x18\x01 \x03(\v2\x11.landlady.ServiceR\bservices\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"3\n" +
	"\x12CheckHealthRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"a\n" +
	"\x13CheckHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"`\n" +
	"\x13WatchServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fhealthy_only\x18\x02 \x01(\bR\vhealthyOnly\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"E\n" +
	"\x14WatchServiceResponse\x12-\n" +
	"\bservices\x18\x01 \x03(\v2\x11.landlady.ServiceR\bservices2\xbd\x03\n" +
	"\x0fLandladyService\x12V\n" +
	"\x0fRegisterService\x12 .landlady.RegisterServiceRequest\x1a!.landlady.RegisterServiceResponse\x12\\\n" +
	"\x11DeregisterService\x12\".landlady.DeregisterServiceRequest\x1a#.landlady.DeregisterServiceResponse\x12P\n" +
	"\rUpdateService\x12\x1e.landlady.UpdateServiceRequest\x1a\x1f.landlady.UpdateServiceResponse\x12V\n" +
	"\x0fDiscoverService\x12 .landlady.DiscoverServiceRequest\x1a!.landlady.DiscoverServiceResponse\x12J\n" +
	"\vCheckHealth\x12\x1c.landlady.CheckHealthRequest\x1a\x1d.landlady.CheckHealthResponse2_\n" +
	"\fWatchService\x12O\n" +
	"\fWatchService\x12\x1d.landlady.WatchServiceRequest\x1a\x1e.landlady.WatchServiceResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_landlady_proto_rawDescOnce sync.Once
	file_proto_landlady_proto_rawDescData []byte
)

func file_proto_landlady_proto_rawDescGZIP() []byte {
	file_proto_landlady_proto_rawDescOnce.Do(func() {
		file_proto_landlady_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_landlady_proto_rawDesc), len(file_proto_landlady_proto_rawDesc)))
	})
	return file_proto_landlady_proto_rawDescData
}

var file_proto_landlady_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_landlady_proto_goTypes = []any{
	(*Service)(nil),                   // 0: landlady.Service
	(*HealthCheck)(nil),               // 1: landlady.HealthCheck
	(*RegisterServiceRequest)(nil),    // 2: landlady.RegisterServiceRequest
	(*RegisterServiceResponse)(nil),   // 3: landlady.RegisterServiceResponse
	(*DeregisterServiceRequest)(nil),  // 4: landlady.DeregisterServiceRequest
	(*DeregisterServiceResponse)(nil), // 5: landlady.DeregisterServiceResponse
	(*UpdateServiceRequest)(nil),      // 6: landlady.UpdateServiceRequest
	(*UpdateServiceResponse)(nil),     // 7: landlady.UpdateServiceResponse
	(*DiscoverServiceRequest)(nil),    // 8: landlady.DiscoverServiceRequest
	(*DiscoverServiceResponse)(nil),   // 9: landlady.DiscoverServiceResponse
	(*CheckHealthRequest)(nil),        // 10: landlady.CheckHealthRequest
	(*CheckHealthResponse)(nil),       // 11: landlady.CheckHealthResponse
	(*WatchServiceRequest)(nil),       // 12: landlady.WatchServiceRequest
	(*WatchServiceResponse)(nil),      // 13: landlady.WatchServiceResponse
	nil,                               // 14: landlady.Service.MetaEntry
	nil,                               // 15: landlady.HealthCheck.ConfigEntry
}
var file_proto_landlady_proto_depIdxs = []int32{
	14, // 0: landlady.Service.meta:type_name -> landlady.Service.MetaEntry
	15, // 1: landlady.HealthCheck.config:type_name -> landlady.HealthCheck.ConfigEntry
	0,  // 2: landlady.RegisterServiceRequest.service:type_name -> landlady.Service
	1,  // 3: landlady.RegisterServiceRequest.health_check:type_name -> landlady.HealthCheck
	0,  // 4: landlady.UpdateServiceRequest.service:type_name -> landlady.Service
	0,  // 5: landlady.DiscoverServiceResponse.services:type_name -> landlady.Service
	0,  // 6: landlady.WatchServiceResponse.services:type_name -> landlady.Service
	2,  // 7: landlady.LandladyService.RegisterService:input_type -> landlady.RegisterServiceRequest
	4,  // 8: landlady.LandladyService.DeregisterService:input_type -> landlady.DeregisterServiceRequest
	6,  // 9: landlady.LandladyService.UpdateService:input_type -> landlady.UpdateServiceRequest
	8,  // 10: landlady.LandladyService.DiscoverService:input_type -> landlady.DiscoverServiceRequest
	10, // 11: landlady.LandladyService.CheckHealth:input_type -> landlady.CheckHealthRequest
	12, // 12: landlady.WatchService.WatchService:input_type -> landlady.WatchServiceRequest
	3,  // 13: landlady.LandladyService.RegisterService:output_type -> landlady.RegisterServiceResponse
	5,  // 14: landlady.LandladyService.DeregisterService:output_type -> landlady.DeregisterServiceResponse
	7,  // 15: landlady.LandladyService.UpdateService:output_type -> landlady.UpdateServiceResponse
	9,  // 16: landlady.LandladyService.DiscoverService:output_type -> landlady.DiscoverServiceResponse
	11, // 17: landlady.LandladyService.CheckHealth:output_type -> landlady.CheckHealthResponse
	13, // 18: landlady.WatchService.WatchService:output_type -> landlady.WatchServiceResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_landlady_proto_init() }
func file_proto_landlady_proto_init() {
	if File_proto_landlady_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_landlady_proto_rawDesc), len(file_proto_landlady_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_landlady_proto_goTypes,
		DependencyIndexes: file_proto_landlady_proto_depIdxs,
		MessageInfos:      file_proto_landlady_proto_msgTypes,
	}.Build()
	File_proto_landlady_proto = out.File
	file_proto_landlady_proto_goTypes = nil
	file_proto_landlady_proto_depIdxs = nil
}
